# Generated by Django 4.2.16 on 2025-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
