# Generated by Django 5.1.4 on 2025-02-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stefbot', '0002_order_amount_alter_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='model_videos/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='stefbot.modelprofile')),
            ],
        ),
    ]
